shared: &shared
  adapter: postgresql
  encoding: unicode
  pool: 5
  
development:
  <<: *shared
  database: high-impact-careers-development
  
test: &test
  <<: *shared
  database: high-impact-careers-test
  timeout: 5000

cucumber:
  <<: *test
