shared: &shared
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

  
development:
  <<: *shared
  database: eighty-thousand-hours-development
  
test: &test
  <<: *shared
  database: eighty-thousand-hours-test
  timeout: 5000

cucumber:
  <<: *test
