development:
  access_key_id: AKIAI4OX2ZMEPGLECJRQ
  secret_access_key: 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
  bucket: eightythousand

production:
  access_key_id: AKIAI4OX2ZMEPGLECJRQ
  secret_access_key: 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
  bucket: eightythousand
